"""Declarative base, naming conventions and shared column mixins.

Every table in the system inherits from ``Base``. Centralising the metadata
here is what lets Alembic autogenerate see the whole schema from a single
import, and what makes constraint names deterministic.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Shared declarative base for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    __mapper_args__ = {"eager_defaults": True}  # noqa: RUF012

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        pk: Any = getattr(self, "id", None)
        return f"<{type(self).__name__} id={pk}>"


class UUIDPrimaryKeyMixin:
    """UUIDv4 primary key, generated by the database.

    Why UUID instead of a serial integer:
      * Sequential integer ids are enumerable — `/orders/1`, `/orders/2` leaks
        volume and invites IDOR probing.
      * A UUID can be generated client-side or in another service without a
        round-trip, which matters once orders are created asynchronously.
    The cost: 16 bytes instead of 4/8, and random insert order fragments
    B-tree indexes slightly. Acceptable at this scale; if it ever stops being
    acceptable the fix is UUIDv7 (time-ordered), not a serial.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """created_at / updated_at maintained by the database clock.

    ``server_default=now()`` and ``onupdate`` on the server side, not in Python:
    application clocks drift and differ between replicas, and rows written by a
    migration or by psql would otherwise have no timestamps at all.

    Columns are timezone-aware (``timestamptz``). PostgreSQL stores those in
    UTC; a naive ``timestamp`` column silently loses the offset and is a
    permanent source of off-by-hours bugs.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
