"""add order shipping addresses

Revision ID: 1b17cc189dd7
Revises: 8f7170e82c04
Create Date: 2026-09-07 17:06:26.220940+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1b17cc189dd7"
down_revision: str | None = "8f7170e82c04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_shipping_addresses",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("recipient_name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("line1", sa.String(length=255), nullable=False),
        sa.Column("line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("region", sa.String(length=120), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "country ~ '^[A-Z]{2}$'",
            name=op.f("ck_order_shipping_addresses_country_iso3166_alpha2"),
        ),
        sa.CheckConstraint(
            "length(btrim(city)) > 0", name=op.f("ck_order_shipping_addresses_city_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(line1)) > 0", name=op.f("ck_order_shipping_addresses_line1_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(recipient_name)) > 0",
            name=op.f("ck_order_shipping_addresses_recipient_name_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_shipping_addresses_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("order_id", name=op.f("pk_order_shipping_addresses")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_shipping_addresses")
    # ### end Alembic commands ###
